### ISSUE TITLE
Failed to pull image "unleashorg/unleash-community-azure:5.9.6"

### ISSUE THREAD

**Issue by iamdmitrij** [Unleash/unleash-docker-community#128]
### Describe the bug

I'm using latest Unleash Helm chart v4.0.0: https://github.com/Unleash/helm-charts/releases/tag/unleash-4.0.0

and in addition to `unleash-community-azure` Docker image for Azure Entra ID authentication.

```
  image:
    repository: unleashorg/unleash-community-azure
```

However, it seems like main Unleash Helm is requesting tag with version `5.9.6` to be in place. As far as I can it doesn't exist on DockerHub yet and main Unleash container deployment breaks with following message:

```
Failed to pull image "unleashorg/unleash-community-azure:5.9.6": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/unleashorg/unleash │
│ -community-azure:5.9.6": failed to resolve reference "docker.io/unleashorg/unleash-community-azure:5.9.6": docker.io/unleashorg/unleash-community-azure:5.9.6: not found
```

https://github.com/Unleash/helm-charts/blob/9b430c25ecfca5ec08fae32ae290489f7760b183/charts/unleash/values.yaml#L147

Are you planning to release latest version so that it would be compatible with latest Unleash Helm chart?

### Unleash version

5.9.6

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

Helm

**Comment by ZanMarolt** [comment]
Hello, thanks for your opened issue, currently the process to create a new community docker image is a manual process and needs manual approval in order to push new version images to the docker hub repository.

I have approved and merged the new version and is being pushed to the dockerhub now.

Please confirm it is now working :)

**Comment by iamdmitrij** [comment]
Works like a charm now :).

Thank you for fixing it.
