### ISSUE TITLE
Docker community image with Google oauth2 passport libraries

### ISSUE THREAD

**Issue by fgaillot-qosenergy** [Unleash/unleash-docker-community#155]
### Describe the feature request

I'm using [Google Auth Hook](https://docs.getunleash.io/using-unleash/deploy/google-auth-hook) to connect to my unleash management interface, but since Unleash v6.0.0, I'm no longer able to use official docker image as mentioned [here](https://docs.getunleash.io/using-unleash/deploy/upgrading-unleash#remove-passport-libs-from-the-official-open-source-docker-distribution). Would it be possible to have a third community image, with all libraries needed to run this hook ?

### Background

It would be useful for all users using Google oauth2 to upgrade to v6.0.0 and above.

### Solution suggestions

Same as the azure image already there, but with the right dependencies in `package.json`.

**Comment by chriswk** [comment]
Feel free to make a PR adding this.

I'd recommend using the OIDC image instead though. Goggle Auth has been deprecated for quite some time

**Comment by ZanMarolt** [comment]
I second @chriswk's opinion on this.

**Comment by fgaillot-qosenergy** [comment]
@chriswk @ZanMarolt I gave it a try, please see attached PR. Feel free to give me any feedbacks
